---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  TestEnv: "TEST"
  nginx.html: |
    <html><head>TEST MESAGE</head>
    <body><h1>1234</h1>
    </body></html>
  nginx.conf: |
    server {
    listen       8080;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
     }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
     }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: netology-14.3
spec:
  containers:
  - name: nginxtest
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    env:
      - name: TestEnv
        valueFrom:
          configMapKeyRef:
            name: nginx
            key: TestEnv
    volumeMounts:
      - name: nginx-vol
        mountPath: /usr/share/nginx/html/
        readOnly: true
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/
  volumes:
  - name: nginx-vol
    configMap:
      name: nginx
      items:
        - key: nginx.html
          path: index.html
  - name: nginx-conf
    configMap:
      name: nginx
      items:
        - key: nginx.conf
          path: default.conf


